[package]
name = "hilbertdust"
version = "0.1.0"
edition = "2021"
default-run = "hilbertdust"

[dependencies]
bytemuck = "1.18.0"
glam = "0.27.0"
itertools = "0.13.0"
sefirot = { path = "../sefirot/sefirot", features = ["glam"] }
sefirot_testbed = { path = "../sefirot/testbed" }
